### ISSUE TITLE
Release iso creator via GH releases?

### ISSUE THREAD

**Issue by moshen** [DRGN-DRC/20XX-HACK-PACK#3]
Can't hurt to have an additional place for these files to exist / mirror. If this omission is explained elsewhere, my apologies.

**Comment by DRGN-DRC** [comment]
No problem. It's not a bad idea. I've been using MediaFire since before I created this repo, so I just kept using that. I also figured the files might be a bit big to include in a repo. GitHub does limit total sizes for files and repositories ([details here](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github)). However after looking into it more, it seems releases follow different rules and can have individual files up to 2 GB, so I might be able to add them here. However I'm confused on whether I need to add them as LFS objects, which have bandwidth restrictions ([described here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-git-lfs-objects-in-archives-of-your-repository)). I'll still need to test it out or read more about it.

**Comment by moshen** [comment]
They would probably be too big to include in the repo. Releases are managed separately. You link a release to a commit or tag, but you can upload your own artifacts

https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository

Looks like there's an individual file size limit of 2GB, but other than that there are no limits according to the docs

https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases

**Comment by DRGN-DRC** [comment]
Alright, I've uploaded v5.0.2 here as a release, and I'll add versions going forward as well. I considered putting up versions 5.0 and 5.0.1, but I thought there was no point. The Source code zips and the code library within those releases wouldn't have been correct for them anymore anyway.

**Comment by moshen** [comment]
Thank you! 🎉
